openapi: 3.0.2
info:
  title: Signup Form
  version: 1.0.0
paths:
  /users:
    get:
      description: Gets all users
      responses:
        '200':
          description: Gets an array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      properties:
        name:
          type: string
        surName:
          type: string
        email:
          type: string
        password:
          type: string