openapi: 3.0.2
info:
  title: Signup Form
  version: 1.0.0
paths:
  /validate:
    post:
      description: Sends form data on the validation service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/User'
      responses:
        '200':
          description: Responces validation errors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ValidationError'
components:
  schemas:
    User:
      properties:
        FirstName:
          type: string
        Surname:
          type: string
        Email:
          type: string
        Password:
          type: string
    ValidationError:
      properties:
        FieldName:
          type: string
        ErrorMessage:
          type: string
